# Generated by Django 4.0.2 on 2022-03-09 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_song_id_remove_user_id_alter_song_song_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.user'),
            preserve_default=False,
        ),
    ]
