# Generated by Django 4.0.2 on 2022-03-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_rating_song_rating_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('date', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('top_genre', models.CharField(max_length=200)),
            ],
        ),
    ]
