# Generated by Django 4.0.2 on 2022-03-09 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='song',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
