# Generated by Django 4.0.2 on 2022-03-10 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.year'),
        ),
    ]
