# Generated by Django 4.0.2 on 2022-04-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_reg_alter_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='password',
        ),
    ]
